name: Nx integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: nrwl/nx-set-shas@v2
      - run: npm ci
      - run: npx nx workspace-lint
      - run: npx nx affected --target=test --parallel=4 --all
      - run: npx nx affected --target=e2e --parallel=4 --all
      - run: npx nx affected --target=build --parallel=4 --all
